name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: mysql
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
        gemfile:
          - Gemfile.rails52
          - Gemfile.rails60
          - Gemfile.rails61
        db:
          - postgresql
          - mysql2
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rspec
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        MYSQL_ROOT_PASSWORD: mysql